addSbtPlugin("org.scalameta"    % "sbt-scalafmt"           % "2.3.2")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"            % "0.5.0")
addSbtPlugin("org.scalastyle"   %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"          % "1.6.1")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"           % "0.9.12")
addSbtPlugin("com.dwijnand"     % "sbt-reloadquick"        % "1.0.0")
addSbtPlugin("io.spray"         % "sbt-revolver"           % "0.9.1")
addSbtPlugin("org.scoverage"    % "sbt-coveralls"          % "1.2.7")
